<a href="https://colab.research.google.com/github/ciccmeek/Michael-Ciccarelli-FNCE-Python/blob/main/Michael%20Ciccarelli%20hw01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HW 01

### Q1. Write a program to input your age and print whether you are more than or less than a billion seconds old.

In [ ]:

age_in_years = int(input("What is your age in years: "))

age_in_seconds = age_in_years * 365 * 24 * 60 * 60

if age_in_seconds > 1000000000:
    print("You are more than a billion seconds old.")
else:
    print("You are less than a billion seconds old.")


What is your age in years: 21
You are less than a billion seconds old.


### Q2. Create a list with 10 names. Print each name with a Good morning greeting with the name using a conditional loop.

For example

`name = ['Ashley', 'Brianna', 'Chetan', 'David', 'Eoin', 'Francois', 'Gemma', 'Hameed', 'Ishaan', 'Joanna']`

Outputs will be 'Good morning, Ashley', 'Good morning, Brianna', and so on.

In [ ]:
## Enter answer here.
name = ['Michael', 'Jack', 'Kevin', 'Jake', 'Alan', 'Blaise', 'Ellie', 'Jamie', 'Bella', 'Ivan']

for i in name:
    print('Good morning, ' + i)


Good morning, Michael
Good morning, Jack
Good morning, Kevin
Good morning, Jake
Good morning, Alan
Good morning, Blaise
Good morning, Ellie
Good morning, Jamie
Good morning, Bella
Good morning, Ivan


### Q3. Create a list of 15 numbers. Print only those numbers that are divisible by 2.

In [ ]:
## Enter answer here.
numbers = list(range(1, 15))

for number in numbers:
    if number % 2 == 0:
      print(number)


2
4
6
8
10
12
14


### Q4. Print the squared numbers of a list containing at least 10 numbers with a mix of float, integer, and negative numbers. Use the longer method as well as list comprehension.

You can either generate your own list of 10 numbers or find use a random number generator.

In [ ]:
## Enter answer here.

nums = [0,-1.25,15.86,-25]
method1_squares = []

for i in nums:
    method1_squares.append(i**2)

print(method1_squares)

## Now method 2


[0, 1.5625, 251.53959999999998, 625]


### Q5. Write a program to print a year if it is a leap year.

In [ ]:
year = int(input())

if year%4 == 0:
    print(year, "is a leap year")
else:
    print(year, "is not a leap year")

2024
2024 is a leap year


### Q6. Use list comprensions to print all names in a list in upper case.

In [ ]:
names = ['Michael', 'Jack', 'Kevin', 'Jake', 'Alan', 'Blaise', 'Ellie', 'Jamie', 'Bella', 'Ivan']
upper_case_names = [name.upper() for name in names]
upper_case_names

['MICHAEL',
 'JACK',
 'KEVIN',
 'JAKE',
 'ALAN',
 'BLAISE',
 'ELLIE',
 'JAMIE',
 'BELLA',
 'IVAN']

### Q7. Question on NUMPY arrays:

a. Create a numpy array called `original` with 100 random numbers. What is the largest number, smallest number, max, min, median, and standard deviation of your array? Print them.

HINT: use `np.random.uniform()`. Check online for the correct syntax. `np.random.rand(100)` will give you 100 random numbers of uniform distribution with mean 0 and standard deviation of 1, while we want a mix of larger numbers/integers.

b. Now create an array called `orig_sqrt` which contains the square roots of the numbers in the original array.

### Q8.  Converting 1D arrays into 2D arrays.

a. Convert your original array of 100 random numbers into a 2-dimensional array called `mat_array` with 20 rows and 5 columns. Print this array.

b. What is the mean of every column in `mat_array`?

c. What is the sum of every row? Create a list of 20 elements that contains the sum of every row in `mat_array`.

d. Create the transpose of `mat_array` and call it `transpose_array`. What are the dimensions of this array now? Again, find the mean of each column and the sum of each row.

### Q9. Array slicing:

a. create a new array which contains the 3rd-10th rows and all columns of `mat_array`. Print.

b. Print a new array which contains the the last 5 rows and the last 2 columns of `mat_array`. What is the dimension of this array?

c. Print a new array which contains the first 3 rows and last 10 columns of `transpose_array`.

In [ ]:
# Write your answer here. Feel free to break your answer into different blocks of code rather than using just this one cell. Label your answer neatly.
import numpy as np

original = np.random.uniform(low=-100, high=100, size=100)

print("Largest number:", np.max(original))
print("Smallest number:", np.min(original))
print("Max:", np.max(original))
print("Min:", np.min(original))
print("Median:", np.median(original))
print("Standard deviation:", np.std(original))

orig_sqrt = np.sqrt(original)



Largest number: 98.45894095128241
Smallest number: -98.27156887483375
Max: 98.45894095128241
Min: -98.27156887483375
Median: 1.7033529740696238
Standard deviation: 56.98030832135982


<ipython-input-16-6158c1f50e1a>:13: RuntimeWarning: invalid value encountered in sqrt
  orig_sqrt = np.sqrt(original)


In [ ]:

import numpy as np

original = np.random.uniform(low=-100, high=100, size=100)
mat_array = original.reshape(20, 5)
print("mat_array:\n", mat_array)

column_means = np.mean(mat_array, axis=0)
print("\nMean of every column in mat_array:\n", column_means)

row_sums = np.sum(mat_array, axis=1)
print("\nSum of every row in mat_array:\n", row_sums)

transpose_array = mat_array.T
print("\nDimensions of transpose_array:", transpose_array.shape)

column_means_transpose = np.mean(transpose_array, axis=0)
print("\nMean of every column in transpose_array:\n", column_means_transpose)

row_sums_transpose = np.sum(transpose_array, axis=1)
print("\nSum of every row in transpose_array:\n", row_sums_transpose)


mat_array:
 [[ 64.90126222 -36.16672355 -94.19221874 -17.21382951 -30.41701945]
 [ 96.03473601   7.29785803 -50.19316649 -36.26489895  31.69258008]
 [-11.44079602  -7.81332082 -15.6589385  -23.21538703  53.29663762]
 [-43.94429946 -53.04159964  87.93068318  65.56108888  52.58536131]
 [ 40.8314686    9.09205548  40.37625322 -96.64169419  56.53129838]
 [-77.18950314 -38.27177032 -79.55303797 -79.58748517  65.4313862 ]
 [-51.80411577  17.72612508   1.1026691  -82.4053339  -82.26113392]
 [ 64.5196376   84.27631367 -38.77958649  65.92416311  48.90515676]
 [-54.97377812  67.10952776 -77.98423644 -83.66129962 -81.33479081]
 [ 33.84817783  -7.47973788 -89.01525605  34.15798046  92.08661703]
 [-39.97620439 -91.36352127 -96.16182019  57.10548746  67.36510726]
 [ 71.91032171 -20.37927018  29.16383212 -75.85453395 -42.42703484]
 [-52.41121382 -83.88301866  48.17405616  72.97613065  68.14038689]
 [-51.28007114  33.73618604 -75.94832926 -38.65356762  80.14015142]
 [-47.0014073   58.76734908  28.8286

In [ ]:

mat_array_slice = mat_array[2:10, :]
print("mat_array_slice:\n", mat_array_slice)

mat_array_slice2 = mat_array[-5:, -2:] # last 5 rows, last 2 columns
print("\nmat_array_slice2:\n", mat_array_slice2)
print("\nDimensions of mat_array_slice2:", mat_array_slice2.shape)

transpose_array_slice = transpose_array[:3, -10:] # first 3 rows, last 10 columns
print("\ntranspose_array_slice:\n", transpose_array_slice)


mat_array_slice:
 [[-11.44079602  -7.81332082 -15.6589385  -23.21538703  53.29663762]
 [-43.94429946 -53.04159964  87.93068318  65.56108888  52.58536131]
 [ 40.8314686    9.09205548  40.37625322 -96.64169419  56.53129838]
 [-77.18950314 -38.27177032 -79.55303797 -79.58748517  65.4313862 ]
 [-51.80411577  17.72612508   1.1026691  -82.4053339  -82.26113392]
 [ 64.5196376   84.27631367 -38.77958649  65.92416311  48.90515676]
 [-54.97377812  67.10952776 -77.98423644 -83.66129962 -81.33479081]
 [ 33.84817783  -7.47973788 -89.01525605  34.15798046  92.08661703]]

mat_array_slice2:
 [[-66.05388355 -78.4168838 ]
 [ 55.99924534  15.28911274]
 [-93.42774329  45.0524409 ]
 [-13.04866801 -48.4776889 ]
 [ 30.69167982  50.36929059]]

Dimensions of mat_array_slice2: (5, 2)

transpose_array_slice:
 [[-39.97620439  71.91032171 -52.41121382 -51.28007114 -47.0014073
  -45.51646693 -52.21521557 -91.6042636   34.9649756   65.26654031]
 [-91.36352127 -20.37927018 -83.88301866  33.73618604  58.76734908
   29

### Q10. Assume you are inviting 15 friends to your party. You guest list has the following dietary preference.

`diet = ['vegetarian', 'pescetarian', 'vegetarian', 'omnivore', 'pescetarian', 'keto', 'keto', 'vegan', 'omnivore', 'omnivore', 'vegan', 'omnivore', 'keto, 'vegetarian', 'vegan']`

Their ages are as follows:

`age = [21, 20, 19, 25, 27, 18, 23, 25, 19, 22, 20, 20, 23, 21, 24]`

Create a list called `menu` which will contain 'veg. fried rice with whiskey' for vegans and vegetarians aged 21 and above,  'veg. fried rice with mocktail' for vegans and vegetarians aged below 21. Follow the same logic and assign fish and white wine to pescetarians of legal age (and fish with mocktail to those below 21). Keto and omnivore guests above 21 will have 'steak and red wine'. Complete the series with the appropriate drink for underage guests.

In [ ]:
# Write your answer here.
import numpy as np

diet = ['vegetarian', 'pescetarian', 'vegetarian', 'omnivore', 'pescetarian', 'keto', 'keto', 'vegan', 'omnivore', 'omnivore', 'vegan', 'omnivore', 'keto', 'vegetarian', 'vegan']
age = [21, 20, 19, 25, 27, 18, 23, 25, 19, 22, 20, 20, 23, 21, 24]

menu = []
for i in range(len(diet)):
  if diet[i] in ('vegetarian', 'vegan'):
    if age[i] >= 21:
      menu.append('veg. fried rice with whiskey')
    else:
      menu.append('veg. fried rice with mocktail')
  elif diet[i] == 'pescetarian':
    if age[i] >= 21:
      menu.append('fish and white wine')
    else:
      menu.append('fish with mocktail')
  elif diet[i] in ('keto', 'omnivore'):
    if age[i] >= 21:
      menu.append('steak and red wine')
    else:
      menu.append('steak and red grape juice') # Assuming a non-alcoholic option for underage guests

menu

['veg. fried rice with whiskey',
 'fish with mocktail',
 'veg. fried rice with mocktail',
 'steak and red wine',
 'fish and white wine',
 'steak and red grape juice',
 'steak and red wine',
 'veg. fried rice with whiskey',
 'steak and red grape juice',
 'steak and red wine',
 'veg. fried rice with mocktail',
 'steak and red grape juice',
 'steak and red wine',
 'veg. fried rice with whiskey',
 'veg. fried rice with whiskey']